# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKPJ3kIxnyYhN5_CqAHL3V5_sOyjSBF3
"""

pip install transformers torch accelerate pandas

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import pandas as pd

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

data = {
    "age": [16, 18, 20],
    "sexe": ["Homme", "Femme", "Homme"],
    "taille": ["M", "S", "L"],
    "style_prefere": ["sport", "casual", "formel"],
    "choix_client": ["t-shirt", "robe", "chemise"]
}

df = pd.DataFrame(data)

def recommander_vetement(age, sexe, taille, style_prefere, choix_client):

    messages = [
        {
            "role": "system",
            "content": "Tu es un assistant expert en mode. Répond uniquement avec 3 tenues. Aucun texte supplémentaire."
        },
        {
            "role": "user",
            "content": f"""
Profil:
âge: {age}
sexe: {sexe}
taille: {taille}
style: {style_prefere}
vêtement: {choix_client}

Format obligatoire:
1) haut + bas + chaussures
2) haut + bas + chaussures
3) haut + bas + chaussures
"""
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=100,
            temperature=0.6,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    # IMPORTANT: remove prompt from output
    input_len = inputs["input_ids"].shape[1]
    output_tokens = outputs[0][input_len:]

    result = tokenizer.decode(output_tokens, skip_special_tokens=True)

    return result.strip()

results = []

for row in df.itertuples(index=False):
    results.append(
        recommander_vetement(
            row.age,
            row.sexe,
            row.taille,
            row.style_prefere,
            row.choix_client
        )
    )

df["recommendation"] = results
df

